### ISSUE TITLE
Unspecific dependency check

### ISSUE THREAD

**Issue by jserv** [dexon-foundation/dexon-consensus#343]
According to current installation guide, `$GOPATH` is set right after script `bin/install_tools.sh` is executed. However, since file `bin/install_tools.sh` depends on the availability of Go runtime, it would be better to adjust the instructions to mention `$GOPATH` first.

In addition, there was a typo: "GOAPTH".

**Comment by jimmyhu-dexon** [comment]
Thanks for reporting. Fixed in #344.
